### ISSUE TITLE
console spammed when close to the doctor menu in any office 

### ISSUE THREAD

**Issue by James-the-Coding-Gamer** [BurntJannings/legacy_medic#1]
![image](https://user-images.githubusercontent.com/26008458/205821763-6feae2af-2ac3-47c6-8920-49e83d21a237.png)
 
this is what is spamming just the word doctor ...

**Comment by James-the-Coding-Gamer** [comment]
like 100 a sec spamming lol

**Comment by BurntJannings** [comment]
Making a change now sorry lol dev debug

**Comment by BurntJannings** [comment]
Fixed and fixed doctor office blips
