### ISSUE TITLE
map blip issue.

### ISSUE THREAD

**Issue by jamiemc71** [BurntJannings/legacy_medic#10]
when someone calls for a doctor if another player picks them up and carry's them to another location and they then re alert the doctor the blip stays in the place where they first called for the doctor, 

could this be changed as from what i can see its a great script.

also im on the lastet version of the script and VORP cord

many thnaks

**Comment by RealStonerGamer** [comment]
alert blips in not part of this script its what ever alert script you use like syn_society or syn_alerts

**Comment by James-the-Coding-Gamer** [comment]
> when someone calls for a doctor if another player picks them up and carry's them to another location and they then re alert the doctor the blip stays in the place where they first called for the doctor,
> 
> could this be changed as from what i can see its a great script.
> 
> also im on the lastet version of the script and VORP cord
> 
> many thnaks


alert blips in not part of this script its what ever alert script you use like syn_society or syn_alerts or bcc-job-alerts

**Comment by jamiemc71** [comment]
hey there,
thank you for the quick reply. i was using bcc-job-alerts but i have now changed to syn_society over night and havnt tryed it using this yet, do i have to change anything somewhere in order for it to use syn_society? or should it just work right out the box

**Comment by James-the-Coding-Gamer** [comment]
> hey there, thank you for the quick reply. i was using bcc-job-alerts but i have now changed to syn_society over night and havnt tryed it using this yet, do i have to change anything somewhere in order for it to use syn_society? or should it just work right out the box

syn_society will do the same it will only remove when the doctor uses /ccalerts if the body is moved it will not move the blip a new one will be put in the new place and the old one will stay till you /calert

**Comment by James-the-Coding-Gamer** [comment]
in the config turn on Config.synsociety = true to use the duty check when and you need to config syn_society with the doctor job and any other job for healing

**Comment by jamiemc71** [comment]
perfect thank you sir

**Comment by jamiemc71** [comment]
@RealStonerGamer  so ive just gone to test this again and upon doing /alertdoctor i get this. 

```
[    c-scripting-core] InvokeNative: execution failed: Argument at index 0 was null.
[    script:vorp_core] SCRIPT ERROR: Execution of native 00000000ff7f66ab in script host failed: Argument at index 0 was null.
[    script:vorp_core] > GetNumPlayerIdentifiers (GetNumPlayerIdentifiers.lua:3)
[    script:vorp_core] > GetSteamID (@vorp_core/server/sv_whitelist.lua:39)
[    script:vorp_core] > ref (@vorp_core/server/sv_apicontroller.lua:110)
[  script:syn_society] SCRIPT ERROR: error object is not a string i get these errors 
```

**Comment by James-the-Coding-Gamer** [comment]
> @RealStonerGamer so ive just gone to test this again and upon doing /alertdoctor i get this.
> 
> ```
> [    c-scripting-core] InvokeNative: execution failed: Argument at index 0 was null.
> [    script:vorp_core] SCRIPT ERROR: Execution of native 00000000ff7f66ab in script host failed: Argument at index 0 was null.
> [    script:vorp_core] > GetNumPlayerIdentifiers (GetNumPlayerIdentifiers.lua:3)
> [    script:vorp_core] > GetSteamID (@vorp_core/server/sv_whitelist.lua:39)
> [    script:vorp_core] > ref (@vorp_core/server/sv_apicontroller.lua:110)
> [  script:syn_society] SCRIPT ERROR: error object is not a string i get these errors 
> ```

like i said before /alertdoctor is a coomand from syn_society not this script ask in syn for issues with there scripts

**Comment by jamiemc71** [comment]
ok

**Comment by James-the-Coding-Gamer** [comment]
feel free to close as this is not a issue with the medic script
