### ISSUE TITLE
Doctor Log Out

### ISSUE THREAD

**Issue by wolfmann2434** [BurntJannings/legacy_medic#8]
when a doctor leaves the server without clocking out manually i get this constantly til i restart the script and the AI doctor will say a Doctor is available
![Screenshot 2023-05-07 001929](https://user-images.githubusercontent.com/80108189/236657408-865bc6ba-849c-482f-a9e8-9812fa4b0ef9.png)
 and not come

**Comment by James-the-Coding-Gamer** [comment]
have you updated to the newest ??? that check was removed and replaced the other day 
 so if that is still checking update the script with what is here on the git hub

**Comment by James-the-Coding-Gamer** [comment]
@BurntJannings  this issue was fixed with a past PR
